.catalog:
  name: "BSC"
  version: "v0.1.0-bsc"
  description: "Brocade SDN Controller 3.2.1"
bsc:
  health_check:
    port: 8181
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
