api:
  image: stackstorm/st2api
  links:
    - mongo
    - rabbitmq

auth:
  image: stackstorm/st2auth
  links:
    - api
    - mongo

notifier:
  image: stackstorm/st2notifier
  links:
    - api
    - mongo
    - rabbitmq

resultstracker:
  image: stackstorm/st2resultstracker
  links:
    - api
    - mongo
    - rabbitmq

rulesengine:
  image: stackstorm/st2rulesengine
  links:
    - api
    - mongo
    - rabbitmq

sensorcontainer:
  image: stackstorm/st2sensorcontainer
  links:
    - api
    - mongo
    - rabbitmq

exporter:
  image: stackstorm/st2exporter
  links:
    - api
    - mongo
    - rabbitmq

actionrunner:
  image: stackstorm/st2actionrunner
  links:
    - api
    - mongo
    - rabbitmq

### External Services
mongo:
  image: mongo

rabbitmq:
  image: rabbitmq
