bsc-server:
  ports:
  - 22:22/tcp
  - 80:80/tcp
  labels:
    io.rancher.sidekicks: bsc-data
  image: takagi:5000/bsc:latest
  volumes_from:
  - bsc-data

bsc-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: bscdata
  image: takagi:5000/bsc:latest
  volumes:
  - /var/log/
