bsc-server:
  ports:
  - 8181:8181/tcp
  - 6653:6653/tcp
  - 5005:5005/tcp
  - 8101:8101/tcp
  labels:
    io.rancher.sidekicks: bsc-data
  image: takagi:5000/bsc:latest
  volumes_from:
  - bsc-data

bsc-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: bscdata
  image: takagi:5000/bsc:latest
  volumes:
  - /var/log/
  - /opt/brocade/bsc/controller/log
