 bsc:
    image: takagi:5000/bsc:latest
    ports:
     - "8181:8181"
     - "6653:6653"
     - "5005:5005"
     - "8101:8101"
    volumes-from:
     - 'bsc-data'
bsc-data:
  image: takagi:5000/bsc:latest
  net: none
  volumes:
    - /opt/brocade/bsc/controller/deploy
  command: /bin/true
  labels:
    io.rancher.container.start_once: true