bsc-server:
  tty: true
  stdin_open: true
  ports:
  - 8181:8181/tcp
  - 6653:6653/tcp
  - 5005:5005/tcp
  - 8101:8101/tcp
  labels:
    io.rancher.sidekicks: bsc-data
  image: takagi:5000/bsc:latest
  volumes_from:
  - bsc-data

bsc-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: bscdata
  image: takagi:5000/bsc:latest
  volumes:
  - data:/opt/brocade/bsc/controller/deploy
  - logs:/opt/brocade/bsc/controller/logs
  volume_driver: convoy-nfs
