bsc-server:
  tty: true
  stdin_open: true
  ports:
  - 8181:8181/tcp
  - 6653:6653/tcp
  - 5005:5005/tcp
  - 8101:8101/tcp
  labels:
    io.rancher.sidekicks: bsc-data
  image: takagi:5000/bsc:latest
  #  - data:/opt/brocade/bsc/controller
  # volume_driver: convoy-nfs
  volumes_from:
  - bsc-data

netopeer:
  tty: true
  stdin_open: true
  ports:
    - 830:830
  image: takagi:5000/netopeer:latest
  volumes:
    - data1:/usr/etc/netopeer
  volume_driver: convoy-nfs


bsc-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: bscdata
  image: takagi:5000/bsc:latest
  volumes:
  - data1:/opt/brocade/bsc/controller/data
  - data1:/opt/brocade/bsc/controller/deploy
  volume_driver: convoy-nfs
